### ISSUE TITLE
Add a limitations section to the README

### ISSUE THREAD

**Issue by dkichler** [Kashoo/ws-limited#2]
The README should clearly describe the limitations of the plugin, specifically around the blocking mechanism used by the rate limiter.

Also, clarify that this is a client-side solution, in case that's not immediately clear.

It may also be good to describe some wise thread pool/executor options in the context of such limitations.  For this reason, it may be good to tackle #3 first.

**Comment by OldSneerJaw** [comment]
Resolved by pull request #6.
